add symfony and php test
restarteco/symfony-exam pull request #1
Opened 2022-09-28 16:29 UTC by rush93

2022-09-28 16:55 UTC, fleox requested changes
https://bonpatron.com/fr/

2022-09-28 16:55 UTC, fleox commented on README.md
> +`docker-copose exec app_exam bash`
```suggestion
`docker-compose exec app_exam bash`
```

2022-09-28 16:55 UTC, fleox commented on exercices/exo-3.md
> +Ouvrir les fichiers `src/Controller/BookController.php` puis analyser le code.
```suggestion
Ouvrir le fichier `src/Controller/BookController.php` puis analyser le code.
```

2022-09-28 16:55 UTC, fleox commented on exercices/exo-1.md
> +Faire une route pour récupérer les auteurs filtrable par un champ de recherche sur le nom ou le prenom, cette route renverra le prénom des auteurs ainsi que le nom de ses livres, et le nombre de livr
```suggestion
Faire une route pour récupérer les auteurs filtrables par un champ de recherche sur le nom ou le prenom, cette route renverra le prénom des auteurs ainsi que le nom de ses livres, et le nombre de livres de chaque auteurs.
```

2022-09-28 16:55 UTC, fleox commented on exercices/exo-1.md
> +Créer une query GRAPHQL pour récupérer un auteur en mettant a disposition le nom des auteurs, ainsi que ces livres.
```suggestion
Créer une query GRAPHQL pour récupérer un auteur en mettant a disposition le nom des auteurs, ainsi que ses livres.
```

2022-09-29 07:55 UTC, TimotheeOng1910 requested changes

2022-09-29 07:55 UTC, TimotheeOng1910 commented on exercices/exo-1.md
> +Créer une query GRAPHQL pour récupérer un auteur en mettant a disposition le nom des auteurs, ainsi que ces livres.
à disposition

2022-09-29 07:55 UTC, TimotheeOng1910 commented on exercices/exo-2.md
> +ouvrir le fichier src/Service/VisitFiles.php et terminer les TODOs en respectant les commentaires décrivant la fonctions.
la fonction

2022-09-29 07:55 UTC, TimotheeOng1910 commented on exercices/exo-4.md
> +fixer les erreurs de [phpstan](https://phpstan.org/writing-php-code/phpdoc-types) ( commande : `vendor/bin/phpstan`).
je sais pas si c'est utile mais peux être preciser qu'il faut entrer dans le docker avant non ?

2022-09-30 08:03 UTC, merged